name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - run: |
        npm install
        npx react-native link
        npx react-native run-android
        chmod +x ./gradlew
        ./gradlew :module:assembleRelease
    - uses: actions/upload-artifact@v3
      with:
        name: zygisk-imgui-modmenu
        path: out/Manet_release/
